sprint 1 (all e2e passed)
ClevertecFrontendLab/sprint1-YauheniZubets pull request #1
Opened 2023-02-01 20:35 UTC by YauheniZubets

2023-02-01 20:51 UTC, dariavorom requested changes

2023-02-01 20:51 UTC, dariavorom commented on src/components/book-data/bookdata.css
> +        padding-bottom: 10px;
Весь закомментированный код удалить

2023-02-01 20:51 UTC, dariavorom commented on src/components/book-history/bookhistory.js
> +    const a = 5;
Что за переменная?)

2023-02-01 20:51 UTC, dariavorom commented on src/components/navigation/navigation.js
> +                        <NavLink to='/books/:business' className={({ isActive }) => isActive ? 'coloredLink' : undefined}><li className='text-normal'>Бизнес-книги <span className='text-light'>14</spa
Создай константу с категориями и промапай. Все однотипное нужно выводить через map. Код чище, кода меньше и читабельнее, нету дублирования

2023-02-01 20:51 UTC, dariavorom commented on src/components/searchbar/search.js
> +                <button type='button' className= {`searchbar-view ${props.view === 'rows' && ' searchbar-white-back' }`} onClick={cbChangeView} value='tile' data-test-id='button-menu-view-window'>
Пересмотри стили этих кнопок, иконка не по центру

2023-02-01 20:51 UTC, dariavorom commented on src/index.js
> +import { BookPage } from './pages/book';
Пересмотри стили приложения для десктопного разрешения, контент по скринам вылазит за пределы видимости

2023-02-01 22:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675288930/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675288930/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675288930/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675288930/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675288930/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675288930/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675288930/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675288930/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675288930/content-window.png)

2023-02-01 22:53 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675291987/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675291987/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675291987/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675291987/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675291987/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675291987/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675291987/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675291987/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675291987/content-window.png)

2023-02-01 23:21 UTC, YauheniZubets commented on src/index.js
> +import { BookPage } from './pages/book';
В скрине, который тут в комментах, для десктопа ширина 1280px самого скрина вместо 1440px. Поэтому и кажется что вылазит за пределы.  Много раз проверил, горизонтального скролла нет, приложение не вылазит. Если я конечно правильно понял замечание)

2023-02-01 23:52 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675295556/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675295556/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675295556/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675295556/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675295556/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675295556/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675295556/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675295556/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675295556/content-window.png)

2023-02-02 04:24 UTC, dariavorom approved these changes

2023-02-02 05:55 UTC, merged